/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal"
import { State } from "shared"
export { State } from "shared"
export namespace Components {
	interface AppRoot {}
	interface CheckFirst {
		state: State
	}
	interface RadioFirst {
		state: State
	}
}
export interface CheckFirstCustomEvent<T> extends CustomEvent<T> {
	detail: T
	target: HTMLCheckFirstElement
}
export interface RadioFirstCustomEvent<T> extends CustomEvent<T> {
	detail: T
	target: HTMLRadioFirstElement
}
declare global {
	interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
	var HTMLAppRootElement: {
		prototype: HTMLAppRootElement
		new (): HTMLAppRootElement
	}
	interface HTMLCheckFirstElementEventMap {
		changeState: State
	}
	interface HTMLCheckFirstElement extends Components.CheckFirst, HTMLStencilElement {
		addEventListener<K extends keyof HTMLCheckFirstElementEventMap>(
			type: K,
			listener: (
				this: HTMLCheckFirstElement,
				ev: CheckFirstCustomEvent<HTMLCheckFirstElementEventMap[K]>,
			) => any,
			options?: boolean | AddEventListenerOptions,
		): void
		addEventListener<K extends keyof DocumentEventMap>(
			type: K,
			listener: (this: Document, ev: DocumentEventMap[K]) => any,
			options?: boolean | AddEventListenerOptions,
		): void
		addEventListener<K extends keyof HTMLElementEventMap>(
			type: K,
			listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
			options?: boolean | AddEventListenerOptions,
		): void
		addEventListener(
			type: string,
			listener: EventListenerOrEventListenerObject,
			options?: boolean | AddEventListenerOptions,
		): void
		removeEventListener<K extends keyof HTMLCheckFirstElementEventMap>(
			type: K,
			listener: (
				this: HTMLCheckFirstElement,
				ev: CheckFirstCustomEvent<HTMLCheckFirstElementEventMap[K]>,
			) => any,
			options?: boolean | EventListenerOptions,
		): void
		removeEventListener<K extends keyof DocumentEventMap>(
			type: K,
			listener: (this: Document, ev: DocumentEventMap[K]) => any,
			options?: boolean | EventListenerOptions,
		): void
		removeEventListener<K extends keyof HTMLElementEventMap>(
			type: K,
			listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
			options?: boolean | EventListenerOptions,
		): void
		removeEventListener(
			type: string,
			listener: EventListenerOrEventListenerObject,
			options?: boolean | EventListenerOptions,
		): void
	}
	var HTMLCheckFirstElement: {
		prototype: HTMLCheckFirstElement
		new (): HTMLCheckFirstElement
	}
	interface HTMLRadioFirstElementEventMap {
		changeState: State
	}
	interface HTMLRadioFirstElement extends Components.RadioFirst, HTMLStencilElement {
		addEventListener<K extends keyof HTMLRadioFirstElementEventMap>(
			type: K,
			listener: (
				this: HTMLRadioFirstElement,
				ev: RadioFirstCustomEvent<HTMLRadioFirstElementEventMap[K]>,
			) => any,
			options?: boolean | AddEventListenerOptions,
		): void
		addEventListener<K extends keyof DocumentEventMap>(
			type: K,
			listener: (this: Document, ev: DocumentEventMap[K]) => any,
			options?: boolean | AddEventListenerOptions,
		): void
		addEventListener<K extends keyof HTMLElementEventMap>(
			type: K,
			listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
			options?: boolean | AddEventListenerOptions,
		): void
		addEventListener(
			type: string,
			listener: EventListenerOrEventListenerObject,
			options?: boolean | AddEventListenerOptions,
		): void
		removeEventListener<K extends keyof HTMLRadioFirstElementEventMap>(
			type: K,
			listener: (
				this: HTMLRadioFirstElement,
				ev: RadioFirstCustomEvent<HTMLRadioFirstElementEventMap[K]>,
			) => any,
			options?: boolean | EventListenerOptions,
		): void
		removeEventListener<K extends keyof DocumentEventMap>(
			type: K,
			listener: (this: Document, ev: DocumentEventMap[K]) => any,
			options?: boolean | EventListenerOptions,
		): void
		removeEventListener<K extends keyof HTMLElementEventMap>(
			type: K,
			listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
			options?: boolean | EventListenerOptions,
		): void
		removeEventListener(
			type: string,
			listener: EventListenerOrEventListenerObject,
			options?: boolean | EventListenerOptions,
		): void
	}
	var HTMLRadioFirstElement: {
		prototype: HTMLRadioFirstElement
		new (): HTMLRadioFirstElement
	}
	interface HTMLElementTagNameMap {
		"app-root": HTMLAppRootElement
		"check-first": HTMLCheckFirstElement
		"radio-first": HTMLRadioFirstElement
	}
}
declare namespace LocalJSX {
	interface AppRoot {}
	interface CheckFirst {
		onChangeState?: (event: CheckFirstCustomEvent<State>) => void
		state: State
	}
	interface RadioFirst {
		onChangeState?: (event: RadioFirstCustomEvent<State>) => void
		state: State
	}
	interface IntrinsicElements {
		"app-root": AppRoot
		"check-first": CheckFirst
		"radio-first": RadioFirst
	}
}
export { LocalJSX as JSX }
declare module "@stencil/core" {
	export namespace JSX {
		interface IntrinsicElements {
			"app-root": LocalJSX.IntrinsicElements["app-root"] &
				JSXBase.HTMLAttributes<HTMLAppRootElement>
			"check-first": LocalJSX.IntrinsicElements["check-first"] &
				JSXBase.HTMLAttributes<HTMLCheckFirstElement>
			"radio-first": LocalJSX.IntrinsicElements["radio-first"] &
				JSXBase.HTMLAttributes<HTMLRadioFirstElement>
		}
	}
}
